### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Julien-Broyard/twetter#1]
hi @Julien-Broyard  I am a graphic artist and i am interested in designing a logo for your project. If you are interested too I will start designing as soon as possible. Hoping for a positive feedback. - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by Julien-Broyard** [comment]
Hey that would be awesome indeed !

**Comment by Tobaloidee** [comment]
thanks for the fast reply..😃 will show you the design here when i am done. Thanks!

**Comment by Julien-Broyard** [comment]
Thank you :smile:

**Comment by Tobaloidee** [comment]
Hi @Julien-Broyard  here's what i came up with! I hope you like it! still open for your opinion..
![TWETTER PRES-01](https://user-images.githubusercontent.com/36028424/55642527-507c9980-5803-11e9-9fc1-77ccf94dd387.png)

**Comment by Julien-Broyard** [comment]
Wow! That's really amazing! Thank you for all your work, I will credit you in the project readme!

**Comment by Tobaloidee** [comment]
so glad that you liked it! 👍😃 i will finalize the files and make a PR with it

**Comment by Tobaloidee** [comment]
here's the PR #2 with the logo upload & readme update..Also, here is the [LINK](https://drive.google.com/drive/u/1/folders/199WzgFQYDfBiH7zJ201bXG-UAAyXEB16)  to my drive where you can download the other versions and formats of you nice logo.

Thanks and best regards! Looking forward to making logos for you other projects.

-Tobaloidee

**Comment by Julien-Broyard** [comment]
Thank you very much for the work you have done! I will make sure to contact you if I need a logo for another project and if you agree of course :smile:

**Comment by Tobaloidee** [comment]
i checked your other projects and maybe I can design for them and show it there..👍

**Comment by Julien-Broyard** [comment]
If you're willing to make another logo it would be really awesome for this project https://github.com/Julien-Broyard/dogpic since I will soon redo entirely this app to make it better and more performant

**Comment by Tobaloidee** [comment]
Yes! can you tell me about Dogpic, what its features and function?

**Comment by Julien-Broyard** [comment]
Sure :smile:

DogPic is a simple website that allows you to search for images of dogs with an API. The website is simple but aims to be fast and ergonomic to be able to quickly search for pictures of cute dogs!

I will redo this app since I've done it a long time ago and I'm willing to make this app better and add new features (If anyone ask for it :laughing: )

**Comment by Tobaloidee** [comment]
Thanks for the info about it @Julien-Broyard  Will open an issue there when  I finished the initial design. 💯

**Comment by Julien-Broyard** [comment]
Thanks again :+1:

**Comment by Tobaloidee** [comment]
How about on your socketio-chat @Julien-Broyard ? what is it more about?

**Comment by Julien-Broyard** [comment]
It's a project that I have made to learn the basics of websockets and socket.io

**Comment by Tobaloidee** [comment]
so it is about communication?

**Comment by Julien-Broyard** [comment]
Sure however it is really simple and has nothing fancy in it :laughing:

**Comment by Tobaloidee** [comment]
I created an issue on the Socketio-Chat repo @Julien-Broyard  for the logo design there.. 👍

**Comment by Julien-Broyard** [comment]
Awesome :+1:
