### ISSUE TITLE
Creating a Privacy Policy Document

### ISSUE THREAD

**Issue by curtwriter** [Julien-Broyard/twetter#3]
Nice one you have here, @Julien-Broyard. I'm hoping Twetter gets to the stage where we can easily download and install its APK file.

I am a writer and can help you create some of the necessary documents for the app like the Privacy Policy document, the FAQ, Contributor's guidelines, etc. if you don't mind

**Comment by Julien-Broyard** [comment]
Sure why not ! However keep in mind that it is only a little project that I've made in order to learn things and have fun
